objects, arrays …
tomsantos07/trilha-fundamentar pull request #20
Opened 2023-02-06 11:38 UTC by tomsantos07

…objects, arrays, interpolacao, agrupamento e declaracao de variaveis + desafio

2023-02-06 11:58 UTC, juliobetta requested changes

2023-02-06 11:58 UTC, juliobetta commented on Javascript/04 advanced practice/06-exercicios.js
> +let addStudent = students.unshift(newStudent)
hmm.. o `unshift` insere na posição 0. arrays em javascript (e na maioria das linguagens) começam pelo índice 0. mas isso depende de como o material se refere a palavra "posição"...

2023-02-06 17:15 UTC, wguilherme approved these changes

2023-02-06 21:05 UTC, tomsantos07 commented on Javascript/04 advanced practice/06-exercicios.js
> +let addStudent = students.unshift(newStudent)
Obrigado pela observação, pois infelizmente cometi o clássico erro de ignorar a posição 0 do Array, como primeira.

2023-02-06 23:48 UTC, juliobetta approved these changes

2023-02-06 23:48 UTC, juliobetta commented on Javascript/04 advanced practice/06-exercicios.js
> +let addStudent = students.splice(1, 0, newStudent)
agora sim, o `splice` resolve! somente uma observação: como ele é uma função impura (ou mutável), ou seja, ela modifica o valor da variável original, não é necessário atribuir o resultado a uma outra variável. e na verdade nem tem efeito prático nesse caso.

2023-02-09 01:07 UTC, tomsantos07 commented on Javascript/04 advanced practice/06-exercicios.js
> +let addStudent = students.splice(1, 0, newStudent)
Anotado! Nesse caso eu venho seguindo um costume de dar console.log nas variáveis, espero lembrar na próxima desse detalhe. Obrigado por mais essa dica.

2023-02-09 16:45 UTC, merged