Desafio mod 3
tomsantos07/trilha-fundamentar pull request #28
Opened 2023-02-12 21:42 UTC by tomsantos07

2023-02-12 22:48 UTC, juliobetta requested changes

2023-02-12 22:48 UTC, juliobetta commented on Javascript/10 exercicios/03-celsius-to-farenheit.js
> +console.log(convertTemp('26', false));
mesma coisa dos comentários dos outros PR. sua função deve retornar um resultado, e não somente exibir o resultado no log. o mesmo vale para a função `familyBalance`. ver explicação [aqui](https://github.com/tomsantos07/trilha-fundamentar/pull/27/files#r1103889277)

2023-02-12 23:02 UTC, juliobetta requested changes

2023-02-12 23:02 UTC, juliobetta commented on Javascript/10 exercicios/03-celsius-to-farenheit.js
> +  Number(celsius, farenheit)
não entendi muito bem o que esse cara ta fazendo aqui.. o correto seria voce verificar se eles são números primeiro e talvez lançar um exceção caso contrário...

2023-02-13 23:55 UTC, tomsantos07 commented on Javascript/10 exercicios/03-celsius-to-farenheit.js
> +console.log(convertTemp('26', false));
Júlio, refiz o exercício acompanhando a aula.

2023-02-14 02:36 UTC, juliobetta requested changes

2023-02-14 02:36 UTC, juliobetta commented on Javascript/10 exercicios/03-celsius-to-farenheit.js
> +console.log(convertTemp('26', false));
acho que voce esqueceu de subir as modificações...

2023-02-14 03:15 UTC, juliobetta approved these changes

2023-02-14 03:15 UTC, juliobetta commented on Javascript/10 exercicios/03-celsius-to-farenheit.js
> +}
correto! somente como um exercício, tente pensar na solução em termos de pequenas outras funções que combinadas, retornam o resultado de uma forma mais declarativa. por exemplo:

1. sua função extrai o numero e a escala de `degree`. poderia ter pequenas funções pra fazer isso. ex:
```javascript
const extractNumberFromDegree = (degree) => parseFloat(degree)
const extractScaleFromDegree = (degree) => degree.replace(extractNumberFromDegree(degree), "")
```
2. uma função de conversão pra cada escala:
```javascript
const celsiusToFahrenheit = (number) => // formula here
const fahrenheitToCelsius = (number) => // formula here
```

... e por ai vai. no final, sua função `convertDegrees` só vai juntar as pecinhas e retornar a solução. ex:

```javascript
function convertDegrees(degree) {
  const value = extractNumberFromDegree(degree)
  const scale = extractScaleFromDegree(degree)
  
  // ... [check whether both scale and value are valid]

  const formula = {
    C: celsiusToFahrenheit,
    F: fahrenheitToCelsius,
    // accept other conversions in the future...
  }[scale];
 
  formula(value)
}
```

é isso!

2023-02-14 03:15 UTC, juliobetta commented on Javascript/10 exercicios/02-fluxo-caixa-familiar.js
> +console.log(familyBalance(incomeSum, expenseSum));
aqui ainda vai retornar um `undefined` indesejado...

2023-02-16 12:49 UTC, merged