subindo desafio para tirar dúvida
tomsantos07/trilha-fundamentar pull request #54
Opened 2023-03-08 16:37 UTC by tomsantos07

Infelizmente não consegui fazer o tailwindcss funcionar com o link href na tag meta. Como devo fazer?

2023-03-09 03:02 UTC, juliobetta approved these changes

2023-03-27 11:04 UTC, juliobetta requested changes

2023-03-27 11:04 UTC, juliobetta commented on Javascript/DOM/10 eventos/06 desafio/index.html
> + class="moda-wrapper invisible fixed bg-gray-500 w-screen h-screen flex items-center justify-center">
```suggestion
 class="modal-wrapper invisible fixed bg-gray-500 w-screen h-screen flex items-center justify-center">
```

2023-03-27 11:04 UTC, juliobetta commented on Javascript/DOM/10 eventos/06 desafio/script.js
> +// script.js:8 Uncaught TypeError: Cannot read properties of null (reading 'classList') at openModalButton.onclick (script.js:8:16)
desculpa a demora... 
então, tem um erro de digitação no nome da sua classe... (veja comentário anterior)

2023-04-06 14:50 UTC, tomsantos07 commented on Javascript/DOM/10 eventos/06 desafio/script.js
> +// script.js:8 Uncaught TypeError: Cannot read properties of null (reading 'classList') at openModalButton.onclick (script.js:8:16)
Poxa, muito obrigado cara! Eu não fazia ideia de que era isso!

2023-04-12 02:57 UTC, juliobetta commented on Javascript/DOM/10 eventos/06 desafio/index.html
> + class="moda-wrapper invisible fixed bg-gray-500 w-screen h-screen flex items-center justify-center">
só pra te lembrar que voce ainda nao corrigiu esse erro de digitação... caso tenha corrigido em outro PR, fica a vontade pra fechar esse. 👍

2023-04-18 20:14 UTC, merged